name: Build Check Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Create Build Environment
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
