name: Ubuntu-latest Build Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Boost
      run: sudo apt-get install -y libboost-all-dev
    - name: Create Build Environment
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
